[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.black]
line-length = 79

[tool.poetry]
authors = ["Tăng Quốc Thái - <tqthai.sdh222@hcmut.edu.vn>"]
description = "BK-IMP repo"
name = "bk-imp"
readme = "README.md"
version = "0.1.0"

[tool.poetry.dependencies]
diagrams = "^0.23.3"
dtw-python = "^1.3.0"
ffmpeg-python = "^0.2.0"
librosa = "^0.10.0.post2"
llvmlite = "==0.39.*"
minio = "^7.1.15"
pandas = "^2"
praat-parselmouth = "^0.4.3"
pyarrow = "^12.0.0"
pydub = "^0.25.1"
pymcd = "^0.2.1"
python = "^3.10"
python-dotenv = "^1.0.0"
scikit-learn = "^1.1.3"
soundfile = "^0.12.1"
tqdm = "^4.64.1"
unidecode = "^1.3.6"
webrtcvad = "^2.0.10"
yt-dlp = "^2023.3.4"

[tool.poetry.group.dev.dependencies]
dvc = {extras = ["gs"], version = "^2.58.2"}
jupyterlab = "==2.*"
nbqa = {extras = ["toolchain"], version = "^1.7.0"}
pre-commit = "^2.20.0"
toml-sort = "^0.23.0"
