[tool.poetry]
name = "bk-imp"
version = "0.1.0"
description = "BK-IMP repo"
authors = ["Tăng Quốc Thái - <tqthai.sdh222@hcmut.edu.vn>"]
readme = "README.md"
packages = [{include = "bk_imp"}]

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.1.3"
ffmpy = "^0.3.0"
google-cloud-storage = "^2.6.0"
m3u8 = "^3.3.0"
py = "^1.11.0"
pydub = "^0.25.1"
pytest = "^7.2.0"
requests = "^2.28.1"
tweepy = "^4.12.1"


[tool.poetry.group.dev.dependencies]
isort = "^5.10.1"
yapf = "^0.32.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
