[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.black]
line-length = 79

[tool.poetry]
authors = ["Tăng Quốc Thái - <tqthai.sdh222@hcmut.edu.vn>"]
description = "BK-IMP repo"
name = "bk-imp"
packages = [{include = "bk_imp"}]
readme = "README.md"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.10"
diagrams = "^0.23.3"
geopy = "^2.3.0"
haversine = "^2.8.0"
minio = "^7.1.15"
pandas = "^1.5.2"
praat-parselmouth = "^0.4.3"
pulp = "^2.7.0"
pyarrow = "^12.0.0"
python-dotenv = "^1.0.0"
scikit-learn = "^1.1.3"
soundfile = "^0.12.1"
tqdm = "^4.64.1"
yt-dlp = "^2023.3.4"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.22.0"
jupyterlab = "^3.6.3"
nbqa = {extras = ["toolchain"], version = "^1.7.0"}
pre-commit = "^2.20.0"
toml-sort = "^0.23.0"
