[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.black]
line-length = 79

[tool.poetry]
authors = ["Tăng Quốc Thái - <tqthai.sdh222@hcmut.edu.vn>"]
description = "BK-IMP repo"
name = "bk-imp"
packages = [{include = "bk_imp"}]
readme = "README.md"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.10"
diagrams = "^0.23.3"
elasticsearch = "^8.5.2"
neo4j = "^5.7.0"
pandas = "^1.5.2"
pyspark = "^3.4.0"
scikit-learn = "^1.1.3"
torch = "^2.0.0"
torch-geometric = "^2.3.1"
torchaudio = "^2.0.1"
torchvision = "^0.15.1"
tqdm = "^4.64.1"
tweepy = "^4.12.1"
pyarrow = "^12.0.0"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.22.0"
jupyterlab = "^3.6.3"
nbqa = {extras = ["toolchain"], version = "^1.7.0"}
pre-commit = "^2.20.0"
toml-sort = "^0.23.0"
