version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: your_database_user
      POSTGRES_PASSWORD: your_database_password
      POSTGRES_DB: your_database_name
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  streamlit_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit_app
    expose:
      - '8501'  # Expose Streamlit app on this port
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=your_database_name
      - DATABASE_USER=your_database_user
      - DATABASE_PASSWORD=your_database_password

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - '80:80'
      - '443:443'  # Add HTTPS port
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro  # Mount your SSL certificates
    depends_on:
      - streamlit_app

volumes:
  pgdata:
