version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: your_database_user
      POSTGRES_PASSWORD: your_database_password
      POSTGRES_DB: your_database_name
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  streamlit_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit_app
    ports:
      - '8501:8501'
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=your_database_name
      - DATABASE_USER=your_database_user
      - DATABASE_PASSWORD=your_database_password

volumes:
  pgdata:
