version: '2'

services:
  neo4j:
    image: neo4j:4.4
    ports:
      - '7474:7474'
      - '7687:7687'
    environment:
      NEO4J_AUTH: none
      NEO4JLABS_PLUGINS: '["graph-data-science"]'
    user: '${UID}:${GID}'
    volumes:
      - neo4j_data:/data
volumes:
  neo4j_data:
    driver: local
